project:
  type: website
  output-dir: docs

website:
  title: "Pesquisa de Núcleos Urbanos Informais"
  site-url: "https://pesquisanui.github.io/website/"
  favicon: "assets/logo-ipea-favicon.png"
  reader-mode: false
  page-footer: 
    center: "Todo o conteúdo deste site está publicado sob a Licença Creative Commons Atribuição 2.5 Brasil<br>© 2022 Instituto de Pesquisa Econômica Aplicada (Ipea)" #[Política de Privacidade](https://www.ipea.gov.br/portal/images/stories/PDFs/211222_declaracao_privacidade_dados_ipea.pdf)<br />[Expediente – Assessoria de Imprensa e Comunicação](https://www.ipea.gov.br/portal/index.php?option=com_content&view=article&id=13651&catid=156)"
    border: true
  navbar:
    title: "**PESQUISA DE <br>NÚCLEOS URBANOS INFORMAIS**"
    background: "#fafafa" #"#fafafa"
    foreground: "#10607E" #"#000000"
    border: true
    search: true
    pinned: true
    right:
      - href: index.qmd
        text: "<nobr>Página inicial</nobr>"
      - href: explorar.qmd
        text: "Explorar"
      - href: dados.qmd
        text: "Dados"
      - href: publicacoes.qmd
        text: "Publicações"
      - href: equipe.qmd
        text: "Equipe"
      - href: "https://github.com/pesquisanui"
        icon: github
#        text: "<nobr>GitHub</nobr>"
        
format:
  html:
    theme: [default, styles.scss]
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Nesta página"
    
execute:
  echo: false
  warning: false
  message: false
  error: false
